// Preset simulation configurations for common use cases
export const PRESETS = {
  quickstart: {
    name: 'Baseline Convergence',
    subtitle: '10 rounds • 5 clients • FedAvg',
    description:
      'Fundamental federated learning workflow demonstrating collaborative training convergence. Ideal for understanding core FL mechanics with clean IID data distribution.',
    estimatedTime: '45-60 seconds',
    icon: '🚀',
    tags: ['beginner', 'fundamentals'],
    config: {
      num_of_rounds: 10,
      num_of_clients: 5,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 5,
      min_evaluate_clients: 5,
      min_available_clients: 5,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'false',
      begin_removing_from_round: 1,
      training_subset_fraction: 0.5,
      num_of_client_epochs: 2,
    },
  },
  quick_sentiment: {
    name: 'Transformer Sentiment',
    subtitle: '5 rounds • 3 clients • DistilBERT',
    description:
      'Federated sentiment analysis using transformer models with LoRA fine-tuning. Demonstrates adversarial resilience against single-client Gaussian noise attacks.',
    estimatedTime: '4-6 minutes',
    icon: '⚡',
    tags: ['intermediate', 'nlp'],
    config: {
      num_of_rounds: 5,
      num_of_clients: 3,
      num_of_malicious_clients: 1,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 3,
      min_evaluate_clients: 3,
      min_available_clients: 3,
      dataset_source: 'huggingface',
      dataset_keyword: null, // Explicitly null for HuggingFace datasets
      hf_dataset_name: 'stanfordnlp/sst2',
      partitioning_strategy: 'iid',
      model_type: 'transformer',
      transformer_model: 'distilbert-base-uncased',
      max_seq_length: 64,
      text_column: 'sentence',
      label_column: 'label',
      use_lora: true,
      lora_rank: 4,
      batch_size: 8,
      num_of_client_epochs: 3,
      training_subset_fraction: 0.005,
      training_device: 'cuda',
      remove_clients: 'false',
      begin_removing_from_round: 1,
      attack_type: 'gaussian_noise',
      attack_ratio: 1.0,
      gaussian_noise_mean: 0,
      gaussian_noise_std: 50,
    },
  },
  convergence: {
    name: 'Non-IID Defense',
    subtitle: '30 rounds • 15 clients • PID Control',
    description:
      'Real-world heterogeneous data distribution with adaptive PID-based client removal. Tests defense effectiveness against multiple malicious clients in challenging conditions.',
    estimatedTime: '2-3 minutes',
    icon: '📊',
    tags: ['advanced', 'data-heterogeneity'],
    config: {
      num_of_rounds: 30,
      num_of_clients: 15,
      num_of_malicious_clients: 4,
      aggregation_strategy_keyword: 'pid',
      min_fit_clients: 15,
      min_evaluate_clients: 15,
      min_available_clients: 15,
      dataset_source: 'local',
      dataset_keyword: 'femnist_niid',
      remove_clients: 'true',
      begin_removing_from_round: 2,
      training_subset_fraction: 0.5,
      num_of_client_epochs: 5,
      batch_size: 20,
      attack_type: 'gaussian_noise',
      attack_ratio: 1.0,
      gaussian_noise_mean: 0,
      gaussian_noise_std: 20,
      Kp: 0.8,
      Ki: 0.05,
      Kd: 0.05,
      num_std_dev: 2.2,
      preserve_dataset: 'false',
    },
  },
  byzantine: {
    name: 'Byzantine Resilience',
    subtitle: '12 rounds • 10 clients • Krum',
    description:
      'Byzantine-robust aggregation defending against coordinated label-flipping attacks. Demonstrates robust distance-based filtering to isolate malicious client updates.',
    estimatedTime: '90-120 seconds',
    icon: '⚔️',
    tags: ['intermediate', 'robust-aggregation'],
    config: {
      num_of_rounds: 12,
      num_of_clients: 10,
      num_of_malicious_clients: 3,
      aggregation_strategy_keyword: 'krum',
      num_krum_selections: 6,
      min_fit_clients: 10,
      min_evaluate_clients: 10,
      min_available_clients: 10,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'true',
      begin_removing_from_round: 2,
      dynamic_attacks: {
        enabled: true,
        schedule: [
          {
            start_round: 3,
            end_round: 8,
            selection_strategy: 'specific',
            client_ids: [0, 1, 2],
            attack_config: {
              type: 'label_flipping',
              params: { flip_fraction: 0.7, num_classes: 62 },
            },
          },
        ],
      },
    },
  },
  medical: {
    name: 'Dirichlet Partitioning',
    subtitle: '10 rounds • 8 clients • Trimmed Mean',
    description:
      'Handwriting recognition with realistic non-IID Dirichlet data heterogeneity. Showcases trimmed mean aggregation for robustness against outlier client behavior.',
    estimatedTime: '2-3 minutes',
    icon: '✍️',
    tags: ['intermediate', 'data-heterogeneity'],
    config: {
      num_of_rounds: 10,
      num_of_clients: 8,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'trimmed_mean',
      trim_ratio: 0.2,
      min_fit_clients: 8,
      min_evaluate_clients: 8,
      min_available_clients: 8,
      dataset_source: 'huggingface',
      hf_dataset_name: 'flwrlabs/femnist',
      partitioning_strategy: 'dirichlet',
      partitioning_params: { alpha: 0.3 },
      model_type: 'cnn',
      label_column: 'character',
      batch_size: 32,
      remove_clients: 'true',
      begin_removing_from_round: 2,
    },
  },
  adaptive_defense: {
    name: 'Adaptive Multi-Phase',
    subtitle: '20 rounds • 12 clients • Dynamic Attacks',
    description:
      'Advanced defense scenario with evolving attack patterns across three distinct phases. PID controller adapts detection thresholds in real-time as threats change.',
    estimatedTime: '2-3 minutes',
    icon: '🛡️',
    tags: ['advanced', 'defense'],
    config: {
      num_of_rounds: 20,
      num_of_clients: 12,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'pid',
      min_fit_clients: 12,
      min_evaluate_clients: 12,
      min_available_clients: 12,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'true',
      begin_removing_from_round: 2,
      Kp: 1.0,
      Ki: 0.05,
      Kd: 0.05,
      num_std_dev: 2.0,
      dynamic_attacks: {
        enabled: true,
        schedule: [
          {
            start_round: 3,
            end_round: 7,
            selection_strategy: 'specific',
            client_ids: [0, 1],
            attack_config: {
              type: 'label_flipping',
              params: { flip_fraction: 0.3, num_classes: 62 },
            },
          },
          {
            start_round: 8,
            end_round: 14,
            selection_strategy: 'specific',
            client_ids: [0, 1, 2, 3],
            attack_config: {
              type: 'gaussian_noise',
              params: { mean: 0, std: 50 },
            },
          },
          {
            start_round: 15,
            end_round: 20,
            selection_strategy: 'specific',
            client_ids: [4, 5, 6],
            attack_config: {
              type: 'label_flipping',
              params: { flip_fraction: 0.8, num_classes: 62 },
            },
          },
        ],
      },
    },
  },
};
