// Preset simulation configurations for common use cases
export const PRESETS = {
  quickstart: {
    name: 'Quick Start',
    subtitle: '5 rounds / 5 clients',
    description:
      'Fast baseline to verify setup. Perfect first simulation for students learning federated learning.',
    estimatedTime: '20-40 seconds',
    icon: '🚀',
    config: {
      num_of_rounds: 5,
      num_of_clients: 5,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 5,
      min_evaluate_clients: 5,
      min_available_clients: 5,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'false',
      begin_removing_from_round: 1,
    },
  },
  convergence: {
    name: 'Convergence Study',
    subtitle: '15 rounds / 8 clients',
    description:
      'PID defense with smooth convergence curves. Best for demos and understanding adaptive defense dynamics.',
    estimatedTime: '60-90 seconds',
    icon: '📈',
    config: {
      num_of_rounds: 15,
      num_of_clients: 8,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'pid',
      min_fit_clients: 8,
      min_evaluate_clients: 8,
      min_available_clients: 8,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'true',
      begin_removing_from_round: 2,
    },
  },
  byzantine: {
    name: 'Byzantine Attack',
    subtitle: 'Dynamic attacks + Krum',
    description:
      'Demonstrates Krum defense against label flipping attacks scheduled in rounds 3-8. Watch defenses adapt in real-time!',
    estimatedTime: '90-120 seconds',
    icon: '⚔️',
    config: {
      num_of_rounds: 12,
      num_of_clients: 10,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'krum',
      num_krum_selections: 6,
      min_fit_clients: 10,
      min_evaluate_clients: 10,
      min_available_clients: 10,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'true',
      begin_removing_from_round: 2,
      dynamic_attacks: {
        enabled: true,
        schedule: [
          {
            start_round: 3,
            end_round: 8,
            selection_strategy: 'specific',
            client_ids: [0, 1, 2],
            attack_config: {
              type: 'label_flipping',
              params: { flip_fraction: 0.7, num_classes: 62 },
            },
          },
        ],
      },
    },
  },
  medical: {
    name: 'Federated Handwriting',
    subtitle: 'FEMNIST + Trimmed Mean',
    description:
      'Federated handwriting recognition with Dirichlet heterogeneity (α=0.3). Demonstrates robust aggregation across distributed writers.',
    estimatedTime: '2-3 minutes',
    icon: '✍️',
    config: {
      num_of_rounds: 10,
      num_of_clients: 8,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'trimmed_mean',
      trim_ratio: 0.2,
      min_fit_clients: 8,
      min_evaluate_clients: 8,
      min_available_clients: 8,
      dataset_source: 'huggingface',
      hf_dataset_name: 'flwrlabs/femnist',
      partitioning_strategy: 'dirichlet',
      partitioning_params: { alpha: 0.3 },
      model_type: 'cnn',
      batch_size: 32,
      remove_clients: 'true',
      begin_removing_from_round: 2,
    },
  },
  sentiment: {
    name: 'Sentiment Analysis',
    subtitle: 'SST2 + Transformer',
    description:
      'Movie review sentiment classification with pathological partitioning. Showcases transformer models and extreme non-IID challenges.',
    estimatedTime: '3-4 minutes',
    icon: '📝',
    config: {
      num_of_rounds: 8,
      num_of_clients: 6,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'fedavg',
      min_fit_clients: 6,
      min_evaluate_clients: 6,
      min_available_clients: 6,
      dataset_source: 'huggingface',
      hf_dataset_name: 'stanfordnlp/sst2',
      partitioning_strategy: 'pathological',
      model_type: 'transformer',
      batch_size: 16,
      num_of_client_epochs: 1,
      remove_clients: 'false',
      begin_removing_from_round: 1,
    },
  },
  adaptive_defense: {
    name: 'Adaptive Defense Showcase',
    subtitle: 'Multi-phase attacks + PID',
    description:
      'Dynamic poisoning attack simulation with adaptive PID defense. Watch attacks intensify while defenses respond in real-time across 3 distinct phases.',
    estimatedTime: '2-3 minutes',
    icon: '🛡️',
    config: {
      num_of_rounds: 20,
      num_of_clients: 12,
      num_of_malicious_clients: 0,
      aggregation_strategy_keyword: 'pid',
      min_fit_clients: 12,
      min_evaluate_clients: 12,
      min_available_clients: 12,
      dataset_source: 'local',
      dataset_keyword: 'femnist_iid',
      remove_clients: 'true',
      begin_removing_from_round: 2,
      Kp: 1.0,
      Ki: 0.05,
      Kd: 0.05,
      num_std_dev: 2.0,
      dynamic_attacks: {
        enabled: true,
        schedule: [
          {
            start_round: 3,
            end_round: 7,
            selection_strategy: 'specific',
            client_ids: [0, 1],
            attack_config: {
              type: 'label_flipping',
              params: { flip_fraction: 0.3, num_classes: 62 },
            },
          },
          {
            start_round: 8,
            end_round: 14,
            selection_strategy: 'specific',
            client_ids: [0, 1, 2, 3],
            attack_config: {
              type: 'gaussian_noise',
              params: { mean: 0, std: 50 },
            },
          },
          {
            start_round: 15,
            end_round: 20,
            selection_strategy: 'specific',
            client_ids: [4, 5, 6],
            attack_config: {
              type: 'label_flipping',
              params: { flip_fraction: 0.8, num_classes: 62 },
            },
          },
        ],
      },
    },
  },
};
